BASE_TASK_CONFIG_PATH: "configs/tasks/explore_replica.yaml"
TRAINER_NAME: "ppoAimasReachability"
ENV_NAME: "NavRLExploration"
SIMULATOR_GPU_ID: 3
TORCH_GPU_ID: 3
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "results/explore2/tb"
VIDEO_DIR: "results/explore2/video_dir"
TEST_EPISODE_COUNT: 2
EVAL_CKPT_PATH_DIR: "results/explore2/checkpoints"
NUM_PROCESSES: 13
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "results/explore2/checkpoints"
NUM_UPDATES: 10000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 50

RL:
  PPO:
    # ppo params
    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50

  REACHABILITY:
    only_intrinsic_reward: True
    experience_buffer_size: 719992
    num_recurrent_steps: 1
    batch_size: 64
    num_train_epochs: 10
    feature_extractor_size: 512
    memory_size: 200
    log_freq: 100
    grid_resolution: 1
    optimizer: "Adam"
    optimizer_args:
      lr: 0.00025
    max_action_distance_k: 5
    negative_sample_multiplier: 5
    curiosity_bonus_scale_a: 0.030
    reward_shift_b: 0.5
    novelty_threshold: 0.5
    similarity_aggregation: "percentile"
    similarity_percentile: 90
